/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectmanagementapp.view;


import java.awt.event.KeyEvent;
import javax.persistence.NoResultException;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import projectmanagementapp.controller.EmployeeProcessor;
import projectmangementapp.model.Employee;

/**
 *
 * @author Skec
 */
public class Authorization extends javax.swing.JFrame {

    /**
     * Creates new form Authorization
     */
    public Authorization() {
        initComponents();
        setTitle(Application.HEADER_APP);
        txtUserEmail.setText("antonio.blatancic21@gmail.com");
        pswPassword.setText("antonio21");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtUserEmail = new javax.swing.JTextField();
        txtSifraDjelatnika = new javax.swing.JLabel();
        pswPassword = new javax.swing.JPasswordField();
        btnLogIn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        jLabel1.setText("E-mail:");

        txtUserEmail.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        txtUserEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserEmailKeyReleased(evt);
            }
        });

        txtSifraDjelatnika.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        txtSifraDjelatnika.setText("Password:");

        pswPassword.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        pswPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pswPasswordKeyReleased(evt);
            }
        });

        btnLogIn.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        btnLogIn.setText("Log In");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnLogIn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                        .addComponent(pswPassword, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtUserEmail, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSifraDjelatnika, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(txtSifraDjelatnika)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pswPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(btnLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserEmailKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER 
                && !txtUserEmail.getText().isEmpty()){
           pswPassword.requestFocus();
        }
    }//GEN-LAST:event_txtUserEmailKeyReleased

    private void pswPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswPasswordKeyReleased
        if(evt.getKeyCode()==KeyEvent.VK_ENTER &&
                pswPassword.getPassword().length>0){
            prijaviSe();
        }
    }//GEN-LAST:event_pswPasswordKeyReleased

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        prijaviSe();
    }//GEN-LAST:event_btnLogInActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField pswPassword;
    private javax.swing.JLabel txtSifraDjelatnika;
    private javax.swing.JTextField txtUserEmail;
    // End of variables declaration//GEN-END:variables

    private void prijaviSe() {
        try{
            if(txtUserEmail.getText().isEmpty()){
                obradiGresku(txtUserEmail, "E-mail required!");
                return;
            }          

            if(pswPassword.getPassword().length==0){
                obradiGresku(pswPassword, "Password required");
                return;
            }

            EmployeeProcessor oo = new EmployeeProcessor();
            Employee e = oo.authorization(txtUserEmail.getText(), pswPassword.getPassword());

            if(e==null){
                obradiGresku(pswPassword, "Email and password invalid");
                return;
            } 


            Application.user=e;
            new MainMenu().setVisible(true);
            dispose();
        
        }catch(NoResultException e){
            obradiGresku(txtUserEmail, "User not found!");
        }
    }
    
    private void obradiGresku(JComponent component, String message){
        component.requestFocus();
        JOptionPane.showMessageDialog(rootPane, message);
    }
}
